# Pre-commit hooks for code quality
# Install with: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100]

  # Python linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # YAML formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML, types-requests, types-aiofiles]
        args: [--ignore-missing-imports]
        files: ^ciris_manager/

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [--skip, B101]
        exclude: tests/

  # Markdown formatting
  # - repo: https://github.com/prettier/pre-commit
  #   rev: v4.0.0-alpha.8
  #   hooks:
  #     - id: prettier
  #       types_or: [markdown, yaml, json]
  #       exclude: ^frontend/
