repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [--fix]
        files: \.py$  # Only run on Python files
      - id: ruff-format
        files: \.py$  # Only run on Python files

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML, types-docker, types-requests, types-python-dateutil]
        args: [--ignore-missing-imports]
        files: \.py$  # Only run on Python files
        exclude: ^(g\.py|tools/grace/)