# Example configuration for CIRISManager
# Copy this file to config.yml and modify as needed

# Manager settings
manager:
  host: 127.0.0.1          # API bind address
  port: 8888               # API port
  agents_directory: /opt/ciris-agents  # Where agent data is stored

# Docker settings
docker:
  compose_file: ./docker-compose.yml   # Path to your docker-compose file
  registry: ghcr.io/cirisai            # Container registry

# Watchdog settings for crash detection
watchdog:
  check_interval: 30       # Seconds between health checks
  crash_threshold: 3       # Number of crashes before marking as crash-looping
  crash_window: 300        # Time window (seconds) for crash counting

# Container management
container_management:
  interval: 300            # Seconds between container updates
  pull_images: true        # Auto-pull latest images

# API settings
api:
  enable_cors: true        # Enable CORS for web frontends
  cors_origins:
    - http://localhost:3000
    - http://localhost:8080

# OAuth settings (optional)
# Configure these for production use
# oauth:
#   client_id: your-oauth-client-id
#   client_secret: your-oauth-client-secret
#   redirect_uri: http://localhost:8888/manager/v1/auth/callback