version: '3.8'

services:
  # Nginx reverse proxy - manages all routing
  nginx:
    image: nginx:alpine
    container_name: ciris-nginx
    network_mode: host  # Use host network to access containers on bridge
    volumes:
      # SSL certificates from host
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Nginx logs
      - /var/log/nginx:/var/log/nginx
      # Mount the single nginx config managed by CIRISManager
      - /home/ciris/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Static files for Manager UI
      - /home/ciris/static:/home/ciris/static:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

  # PostgreSQL for telemetry storage
  postgres:
    image: postgres:14-alpine
    container_name: ciris-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ciris
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme_in_production}
      POSTGRES_DB: telemetry
    ports:
      - "127.0.0.1:5432:5432"  # Only bind to localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deploy/init-telemetry-complete.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ciris -d telemetry"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - ciris-network

  # CIRISManager API service (if running containerized)
  # Uncomment if you want to run manager in container instead of systemd
  # ciris-manager:
  #   image: ghcr.io/cirisai/ciris-manager:latest
  #   container_name: ciris-manager
  #   ports:
  #     - "127.0.0.1:8888:8888"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./config.yml:/etc/ciris-manager/config.yml:ro
  #     - /home/ciris/nginx:/home/ciris/nginx
  #   environment:
  #     - CIRIS_MANAGER_CONFIG=/etc/ciris-manager/config.yml
  #   restart: unless-stopped
  #   networks:
  #     - ciris-network

volumes:
  postgres_data:

networks:
  ciris-network:
    name: ciris-network
    driver: bridge