name: Deploy CIRISManager

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual deployment

jobs:
  # First ensure CI passes
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[dev]

      - name: Run linting
        run: |
          ruff check ciris_manager/
          ruff format --check ciris_manager/

      - name: Run type checking
        run: |
          mypy ciris_manager/

      - name: Run tests
        run: |
          python -m pytest tests/ -v --cov=ciris_manager --cov-report=term-missing

      # Build TypeScript SDK
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build TypeScript Manager SDK
        run: |
          cd sdk/typescript/packages/cirismanager-sdk
          npm ci
          npm run build
          npm run build:browser
          npm test

      - name: Verify SDK builds
        run: |
          echo "=== Manager SDK ==="
          ls -la sdk/typescript/packages/cirismanager-sdk/dist/ || true
          ls -la sdk/typescript/packages/cirismanager-sdk/dist-browser/ || true
          test -f sdk/typescript/packages/cirismanager-sdk/dist-browser/cirismanager-sdk.js || echo "Manager SDK browser build not found"

  deploy:
    name: Deploy to Production
    needs: ci  # Only deploy if CI passes
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.repository == 'CIRISAI/CIRISManager'
    environment: production

    steps:
      - name: Deploy CIRISManager
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 108.61.119.117
          username: root
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            set -e

            echo "Deploying CIRISManager..."

            # Ensure base directory exists
            mkdir -p /opt

            # Clone or update repository
            if [ ! -d "/opt/ciris-manager" ]; then
              echo "First time deployment - cloning repository..."
              git clone https://github.com/CIRISAI/CIRISManager.git /opt/ciris-manager
            else
              echo "Updating existing deployment..."
              cd /opt/ciris-manager
              git fetch origin
              git reset --hard origin/main
            fi

            cd /opt/ciris-manager

            # Ensure docker-compose-production.yml exists
            if [ ! -f "docker-compose-production.yml" ]; then
              echo "Error: docker-compose-production.yml not found!"
              echo "Contents of /opt/ciris-manager:"
              ls -la
              exit 1
            fi

            # Create virtual environment if it doesn't exist
            if [ ! -d "venv" ]; then
              echo "Creating virtual environment..."
              python3 -m venv venv
            fi

            # Activate venv and update dependencies
            source venv/bin/activate
            pip install --upgrade pip >/dev/null
            pip install -r requirements.txt >/dev/null
            pip install -e . >/dev/null

            # Ensure config directory exists
            mkdir -p /etc/ciris-manager

            # Generate default config if it doesn't exist
            if [ ! -f "/etc/ciris-manager/config.yml" ]; then
              echo "Generating default configuration..."
              ciris-manager --generate-config --config /etc/ciris-manager/config.yml
            fi

            # Create update script if it doesn't exist
            if [ ! -f "/usr/local/bin/ciris-manager-update" ]; then
              cat > /usr/local/bin/ciris-manager-update << 'SCRIPT'
            #!/bin/bash
            cd /opt/ciris-manager
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pip install -e .
            systemctl restart ciris-manager
            echo "CIRISManager updated successfully"
            SCRIPT
              chmod +x /usr/local/bin/ciris-manager-update
            fi

            # Update systemd service file (always copy to ensure latest version)
            echo "Updating systemd service file..."
            cp /opt/ciris-manager/deployment/ciris-manager.service /etc/systemd/system/
            systemctl daemon-reload

            # Enable service if not already enabled
            if ! systemctl is-enabled ciris-manager >/dev/null; then
              systemctl enable ciris-manager
            fi

            # Ensure ciris-manager user exists and is in correct groups
            if ! id "ciris-manager" &>/dev/null; then
              useradd -r -s /bin/false -d /var/lib/ciris-manager -c "CIRIS Manager Service" ciris-manager
            fi

            # Create ciris group if it doesn't exist
            if ! getent group ciris &>/dev/null; then
              groupadd ciris
            fi

            # Add ciris-manager to necessary groups
            usermod -aG docker ciris-manager
            usermod -aG ciris ciris-manager

            # Fix permissions on existing nginx directory
            chown -R ciris-manager:ciris /home/ciris/nginx
            chmod 775 /home/ciris/nginx

            # Ensure ciris home directory has proper permissions for group access
            chmod 755 /home/ciris

            # Copy static files for manager UI and jailbreaker
            echo "Deploying static files..."
            mkdir -p /home/ciris/static/manager
            mkdir -p /home/ciris/static/jailbreaker
            cp -r /opt/ciris-manager/static/manager/* /home/ciris/static/manager/
            cp -r /opt/ciris-manager/static/jailbreaker/* /home/ciris/static/jailbreaker/

            chown -R ciris-manager:ciris /home/ciris/static
            chmod -R 755 /home/ciris/static

            # Ensure environment file exists and update deployment token
            if [ ! -f "/etc/ciris-manager/environment" ]; then
              echo "# Auto-generated environment file for CIRISManager" > /etc/ciris-manager/environment
            fi

            # Update or add CIRIS_DEPLOY_TOKEN without overwriting other variables
            # Use proper temp file handling to preserve all existing variables
            if grep -q "^CIRIS_DEPLOY_TOKEN=" /etc/ciris-manager/environment; then
              # Remove existing CIRIS_DEPLOY_TOKEN line and add new one
              cp /etc/ciris-manager/environment /tmp/env_backup
              grep -v "^CIRIS_DEPLOY_TOKEN=" /tmp/env_backup > /tmp/env_temp
              echo "CIRIS_DEPLOY_TOKEN=${{ secrets.CIRIS_DEPLOY_TOKEN }}" >> /tmp/env_temp
              # Atomic replacement
              mv /tmp/env_temp /etc/ciris-manager/environment
              rm -f /tmp/env_backup
            else
              echo "CIRIS_DEPLOY_TOKEN=${{ secrets.CIRIS_DEPLOY_TOKEN }}" >> /etc/ciris-manager/environment
            fi

            chmod 600 /etc/ciris-manager/environment

            # Deploy or update nginx container
            echo "Updating nginx container..."
            cd /opt/ciris-manager

            # Pull latest nginx image
            docker-compose -f docker-compose-production.yml pull nginx >/dev/null 2>&1 || true

            # Use up -d which handles existing containers properly
            docker-compose -f docker-compose-production.yml up -d nginx >/dev/null 2>&1 || {
              echo "Failed to start nginx with docker-compose, trying direct restart..."
              docker restart ciris-nginx >/dev/null 2>&1 || echo "Warning: Could not restart nginx"
            }

            # Restart CIRISManager
            echo "Restarting CIRISManager..."
            systemctl restart ciris-manager

            # Verify service started successfully
            sleep 3
            if ! systemctl is-active --quiet ciris-manager; then
              echo "ERROR: CIRISManager failed to start!"
              echo "Service status:"
              systemctl status ciris-manager --no-pager || true
              echo "Recent logs:"
              journalctl -u ciris-manager --no-pager -n 100 || true
              exit 1
            fi

            echo "Service restarted successfully, checking health endpoint..."

            # Wait for service to be ready
            echo "Waiting for CIRISManager API to be ready..."
            for i in {1..30}; do
              if curl -sf http://localhost:8888/manager/v1/health 2>/dev/null; then
                echo "✓ CIRISManager is healthy and responding!"
                break
              fi
              if [ $i -eq 30 ]; then
                echo "ERROR: CIRISManager health check failed after 60 seconds!"
                echo "Service status:"
                systemctl status ciris-manager --no-pager || true
                echo "Recent logs:"
                journalctl -u ciris-manager --no-pager -n 100 || true
                echo "Port check:"
                netstat -tlnp | grep 8888 || true
                exit 1
              fi
              echo "Waiting for API... (attempt $i/30)"
              sleep 2
            done

            echo "Deployment complete!"

      - name: Verify Deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 108.61.119.117
          username: root
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            # Check service status
            echo "=== Service Status ==="
            systemctl status ciris-manager --no-pager || true

            # Check API health
            echo -e "\n=== API Health Check ==="
            curl -s http://localhost:8888/manager/v1/health | jq . || echo "Health check failed"

            # Check nginx status
            echo -e "\n=== Nginx Status ==="
            docker ps | grep nginx || echo "Nginx container not running"

            # Show recent logs
            echo -e "\n=== Recent Logs ==="
            journalctl -u ciris-manager --no-pager -n 20
